Feature/15442 async sql
ARKlab/Ark.Tools pull request #151
Opened 2024-04-24 13:41 UTC by PeterRimmer71

Create Async SQL merge into net8 feature.

2024-04-25 18:08 UTC, AndreaCuneo requested changes
remove all changes from ftpclient which has nothing to do with this PR

2024-04-25 18:15 UTC, AndreaCuneo requested changes

2024-04-25 18:15 UTC, AndreaCuneo commented on Ark.Tools.Outbox.Rebus/OutboxAsyncTransportDecorator.cs
this code is a copy of the sync one for just a minor change.
consolidate so that logic is not duplicated.

2024-04-25 18:15 UTC, AndreaCuneo commented on Ark.Tools.Outbox.Rebus/RebusOutboxAsyncProcessor.cs
same.

2024-04-25 18:15 UTC, AndreaCuneo commented on Ark.Tools.Outbox.SqlServer/AbstractSqlContextFactory.cs
> +                var transaction = vt?.GetAwaiter().GetResult();
????

2024-04-25 18:15 UTC, AndreaCuneo commented on Ark.Tools.Outbox.SqlServer/OutboxContextSqlAsync.cs
this is a duplication with a lot of query and other logic. Consolidate to avoid code duplication.

2024-04-25 18:15 UTC, AndreaCuneo commented on Ark.Tools.Outbox/IOutboxAsyncProducer.cs
same

2024-04-25 18:15 UTC, AndreaCuneo commented on Ark.Tools.Sql/AbstractSqlContextAsync.cs
> +#if !(NETSTANDARD2_0 || NET472)
and ELSE is an empty method?!

please refactor.

2024-04-25 18:15 UTC, AndreaCuneo commented on Ark.Tools.Outbox.SqlServer/AbstractSqlContextFactory.cs
> +        public async ValueTask CreateAsync(string connectionString, IsolationLevel isolationLevel, CancellationToken ctk)
Create implies a 'Factory' which this isn't as doesn't return anything but mutate the class.
This isn't a Factory and this isn't a Create method.

2024-05-03 08:57 UTC, PeterRimmer71 commented
@AndreaCuneo, I branched this feature from master and merged the net8 branch into it. So, the ftp client changes are related to changes in master between when this was branched from master and when net8 was branched. Maybe, I should restart and just branch from net8 and then create the PR comparing to net8.

2024-05-03 10:38 UTC, AndreaCuneo commented
Yes please otherwise you're mixing your changes with a integration with master.

If you need the changed stuff from master, please integrate master into net8

2024-05-16 09:16 UTC, closed without merging