Added the DeleteFile and DeleteDirectory to the FTP client libraries
ARKlab/Ark.Tools pull request #20
Opened 2023-01-17 07:53 UTC by mortoize

2023-01-18 14:58 UTC, AndreaCuneo requested changes
@mortoize thank you for your feature contribution.

I've flagged a few changes, but overall I'm fine with accepting this and release once ready.
Cheers

2023-01-18 14:58 UTC, AndreaCuneo commented on Ark.Tools.FtpClient.FluentFtp/FluentFtpClientConnection.cs
> +using Microsoft.Identity.Client;
this should not be needed

2023-01-18 14:58 UTC, AndreaCuneo commented on Ark.Tools.FtpClient.SystemNetFtpClient/SystemNetFtpClientConnection.cs
> +using Microsoft.Identity.Client;
ditto

2023-01-18 14:58 UTC, AndreaCuneo commented on global.json
> -    "version": "6.0.403",
currently we don't aim to target net7 as is not LTS.
please revert to .net 6.0

2023-01-18 14:58 UTC, AndreaCuneo commented on Directory.Build.props
> +    <TargetFrameworks>net7.0;net6.0;netstandard2.1;netstandard2.0;net472</TargetFrameworks>
currently we don't aim to target net7 as is not LTS.
please revert this.

2023-01-18 16:21 UTC, mortoize commented
> I've flagged a few changes, but overall I'm fine with accepting this and release once ready. Cheers

@AndreaCuneo Thank you for your input. The changes you've requested are done. Hope, everything goes well.

2023-01-19 10:04 UTC, AndreaCuneo approved these changes

2023-01-19 10:04 UTC, merged

2023-01-19 15:09 UTC, AndreaCuneo commented
included in v4.7.0