make InstantHandler support Int64
ARKlab/Ark.Tools pull request #56
Opened 2023-03-21 08:29 UTC by kwon0408

2023-03-22 09:23 UTC, AndreaCuneo commented
Hi @kwon0408 

thanks for the improvement but I cannot accept it as it is.

The issue is that there is no Standard for precision over int64 representation. Different system encode a different precision:
- Windows use 100ns (Ticks)
- POSIX use 1s, same as `int`
- Java use 1ms

Indeed Nodatime support all 3 creators: [`FromUnixTimeTicks`](https://nodatime.org/3.1.x/api/NodaTime.Instant.html#NodaTime_Instant_FromUnixTimeTicks_System_Int64_), [`FromUnixTimeSeconds`](https://nodatime.org/3.1.x/api/NodaTime.Instant.html#NodaTime_Instant_FromUnixTimeSeconds_System_Int64_), [`FromUnixTimeMilliseconds`](https://nodatime.org/3.1.x/api/NodaTime.Instant.html#NodaTime_Instant_FromUnixTimeMilliseconds_System_Int64_)

So I cannot accept in a library to arbitrary choose one.

In addition, this makes this asymmetric with the [`SetValue()`](https://github.com/ARKlab/Ark.Tools/blob/4e48d9f39efce124b249962ee83efb9ebebcdb99/Ark.Tools.Nodatime.Dapper/InstantHandler.cs#L24) in parameters, which would you require to still convert manually when using Dapper parameters as not Instant is passed to SQL as `Datetime`

```cs
connection.ExecuteAsync("INSERT ...", new { Timestamp = instant.ToUnixTimeTicks() });
```

To support this scenario I see 2 acceptable options which I can merge:
1. Implement multiple versions of the InstantHandler. The current one as-is, and 3 more, one per precision, with symmetric support in the SetValue() and Parse() methods. Add a parameter in the [Setup(InstantRepresentation = Datetime)](https://github.com/ARKlab/Ark.Tools/blob/4e48d9f39efce124b249962ee83efb9ebebcdb99/Ark.Tools.Nodatime.Dapper/NodaTimeDapper.cs#LL7C29-L7C29)
2. Add a InstantAsTicks valueobject struct, with implicit conversion from/to Instant and add an Handler for that. This can be used in the class/dto in in Query<T> and Paramters instead of Instants. Since often the same `class` is used also for Json serialization, we would have to add the same support in Json Converters. (Ark.Tools.Nodatime.Json, Ark.Tools.Nodatime.SystemTextJson).

2023-03-23 05:23 UTC, kwon0408 commented
Thank you for the advice.

I chose the option 1, reverted the original `InstantHandler`, added 3 new handlers and a parameter to `Setup()` with default value for the original one.

2023-03-23 09:24 UTC, AndreaCuneo commented on Ark.Tools.Nodatime.Dapper/NodaTimeDapper.cs
> +                default:
please case `InstantHandlerType.DateTime` and throw `NotImplemented()` on default. In this case we don't have a fallback but a 1:1 match to a list of options.

2023-03-23 09:25 UTC, AndreaCuneo commented on Ark.Tools.Nodatime.Dapper/InstantTickHandler.cs
> +using NodaTime.Text;
I think this is unused now. please remove unsued `using`

2023-03-23 09:25 UTC, AndreaCuneo commented on Ark.Tools.Nodatime.Dapper/InstantHandlerType.cs
> +﻿using System;
remove unused using.

2023-03-23 09:31 UTC, AndreaCuneo commented
@kwon0408
I've commented a couple of code-quality changes. Once fixed I'm willing to merge this and release a minor.

Thanks a lot for the contributions.

2023-03-24 09:04 UTC, AndreaCuneo requested changes
please fix compilation errors.

2023-03-28 10:52 UTC, AndreaCuneo commented
Hi @kwon0408 

I've a v4.8 release planned this week, would be grand if I can include this too.

Currently it's failing to build, looks a trivial missing `using`. If you can refresh the branch with a fix I'm going to merge it.

2023-03-29 05:09 UTC, kwon0408 commented
The build was successful after adding 1 `using` line.

2023-03-29 09:02 UTC, merged

2023-03-29 09:23 UTC, AndreaCuneo commented
Included in v4.8.0-beta04 and onward.